version = "0.1.1"
slug = "split-file"
bundle = [ "/docs/README.pdf", "/tests", "/main.py", "/vendor.py", "/data/*input*", "/data/*expected*"]
backup_on_update = [ "/main.py",]
exclude_from_zip = [ "*.pyc", ".DS_Store", "/.git", "*.bak", "*cache*", "/args.py", "/data/*output*",]

[release_notes]
"0.1.0" = "Primera versión"
"0.1.1" = "Ajusta gestión de ficheros output para tests"
