import os

import pytest

if os.path.exists('solution.py'):
    from solution import DNA
else:
    from main import DNA  # type:ignore


DNA_SEQ1 = """
TTGATGCCTAGCTTATGTCATGCGCCGCCCGCACGACTCGATAGCAGCATCGCCCGTTGTATAATTAAAACCCAAGATAT
AACGTACTCCCAAGGTCACGAAGAGAACCCCATGGGAGCGCATACGTGAAGTCTCACCCACAAAACGCCGGCTTCTAGCC
AGCGAGTCCGTCCCTAGAGGCGAATTCGGAAATACTTGCGAGTGAAGAGCGACATTGTTCTTCAGGCCGAATGGCAATAT
CAAAAGAGGTTCATGATCATTTATTTTGTACTACGTAGGTATGCGAACTGTTTAAGCTGCTACGATTTTCACGACTAGAG
""".replace('\n', '')

DNA_SEQ2 = """
CAACGTGCGTGGGCTCCTGGACTACAGGTCCGTGTGGTGTACAAGCAAGGATACTCCGCAGGTTGAAGGTCAGCCCGGTT
ACGTCAGCCGGTCAACTATACGGTCTTACAGGCATATGATCTGTCCCGAAGTGGGATTACATGTCGCGAATGGGACATTA
CCCTTGGCGTCGTACGCTGCGTTGTGCGAATAGTTCGTCCCTTTCTACGCCATTTTAAAGTCTCCTCGTGCGTAGTGCTT
CGCTAGTCTCGTCGTCTAGACATGCCGAAGCAACCTCGCGATTGTCGCAATATCAGAACCCTTTGAAATTTGCGCAGCCA
""".replace('\n', '')

DNA_SEQ3 = """
AACGTACTCCCAAGGTCACGAAGAGAACCCCATGGGAGCGCATACGTGAAGTCTCACCCACAAAACGCCGGCTTCTAGCC
CGCTAGTCTCGTCGTCTAGACATGCCGAAGCAACCTCGCGATTGTCGCAATATCAGAACCCTTTGAAATTTGCGCAGCCA
""".replace('\n', '')


@pytest.fixture
def dna1():
    return DNA(DNA_SEQ1)


@pytest.fixture
def dna2():
    return DNA(DNA_SEQ2)


@pytest.fixture
def dna3():
    return DNA(DNA_SEQ3)
